"""Export the undecompiled RAC2 baseline in objdiff report v2 format."""

from __future__ import annotations

import argparse
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]


def measures(code_size: int, data_size: int, units: int) -> dict:
    return {"totalCode": str(code_size), "matchedCode": "0", "matchedCodePercent": 0,
            "totalData": str(data_size), "matchedData": "0", "matchedDataPercent": 0,
            "completeCode": "0", "completeCodePercent": 0, "completeData": "0",
            "completeDataPercent": 0, "fuzzyMatchPercent": 0,
            "totalUnits": units, "completeUnits": 0}


def generate(scope: dict, target: dict, overlays: dict, progress: dict) -> dict:
    if scope["target"] != target["serial"] or overlays["target"] != target["serial"]:
        raise ValueError("Progress scope belongs to another target")
    if progress["decompiled_functions"] != 0:
        raise ValueError("Baseline exporter cannot report new C/C++ matches; replace with verified objdiff units")
    expected = {"boot": target["boot"]["sha256"],
                **{"levels/" + entry["level"]: entry["sha256"] for entry in overlays["levels"]}}
    programs = scope["programs"]
    actual = {program["name"]: program["sha256"] for program in programs}
    if len(programs) != 28 or len(actual) != len(programs) or actual != expected:
        raise ValueError("Progress scope must cover the pinned boot and all 27 overlays")
    units = []
    total_code = 0
    total_data = 0
    seen_names = set()
    for program in programs:
        for section in program["sections"]:
            size = section["size"]
            if type(size) is not int or size <= 0 or not section["flags"] & 2 or section["type"] != 1:
                raise ValueError("Progress scope requires positive, allocated PROGBITS sections")
            name = f"{program['name']}/{section['name']}@{section['address']:08X}"
            if name in seen_names:
                raise ValueError("Duplicate progress unit")
            seen_names.add(name)
            is_code = bool(section["flags"] & 4)
            code_size = size if is_code else 0
            data_size = 0 if is_code else size
            total_code += code_size
            total_data += data_size
            category = "boot" if program["name"] == "boot" else "levels"
            units.append({"name": name, "measures": measures(code_size, data_size, 1),
                          "sections": [{"name": section["name"], "size": str(size),
                                        "fuzzyMatchPercent": 0,
                                        "metadata": {"virtualAddress": str(section["address"])}}],
                          "metadata": {"complete": False, "autoGenerated": True,
                                       "moduleName": program["name"], "progressCategories": [category]}})
    if not total_code:
        raise ValueError("Empty executable progress scope")
    categories = []
    for category, title in (("boot", "Boot ELF"), ("levels", "27 level overlays")):
        subset = [unit for unit in units if category in unit["metadata"]["progressCategories"]]
        categories.append({"id": category, "name": title,
                           "measures": measures(sum(int(unit["measures"]["totalCode"]) for unit in subset),
                                                sum(int(unit["measures"]["totalData"]) for unit in subset),
                                                len(subset))})
    return {"version": 2, "measures": measures(total_code, total_data, len(units)),
            "units": units, "categories": categories}


def main() -> int:
    parser = argparse.ArgumentParser(description="Export the explicit 0% C/C++ RAC2 baseline")
    parser.add_argument("--output", required=True, type=Path)
    args = parser.parse_args()
    def read(relative: str) -> dict:
        return json.loads((ROOT / relative).read_text(encoding="utf-8"))
    report = generate(read("config/progress-scope.json"), read("config/target.json"),
                      read("config/overlays.json"), read("progress/report.json"))
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(json.dumps(report, indent=2) + "\n", encoding="utf-8")
    print(json.dumps({"output": str(args.output), "units": len(report["units"]),
                      "total_code": report["measures"]["totalCode"], "matched_code": "0"}))
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except (OSError, ValueError, KeyError) as error:
        print(f"Report export failed: {error}")
        raise SystemExit(2)
